name: "CodeMeta to Zenodo Converter"
description: "Convert codemeta.json to .zenodo.json and validate the output"
branding:
  icon: "file-text"
  color: "blue"

inputs:
  codemeta_file:
    description: "Path to the codemeta.json file"
    required: false
    default: "codemeta.json"
  overwrite:
    description: "Overwrite existing .zenodo.json file if it exists"
    required: false
    default: "false"
  add_escape2020:
    description: "Add ESCAPE2020 community and grant number to .zenodo.json"
    required: false
    default: "false"

outputs:
  zenodo_file:
    description: "Path to the generated .zenodo.json file"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.codemeta_file }}
    - ${{ inputs.overwrite }}
    - ${{ inputs.add_escape2020 }}
